### ISSUE TITLE
support for GFA

### ISSUE THREAD

**Issue by ekg** [TF-Chan-Lab/panGraphViewer#1]
Does this support GFA with genomes represented as Path records (as in vg and pggb)?

**Comment by yuxuanyuan** [comment]
We were also thinking to support GFA. However, it seems some of the GFA files generated from tools, such as ``vg`` has no sample information, which makes the display of a graph less informative, for instance where specific nodes come from. 
By the way, In this tool, we also support ``VCF``. We can add functions to support ``GFA_v1`` and ``GFA_v2`` in later update if needed.

**Comment by ekg** [comment]
Most of the pangenome graphs that are built do not have sample information.
It is frequently not available because diploid assemblies are difficult to
obtain. In most cases, we have assemblies. In that case it's as if each
sample is haploid.

Where sample information is included, it is typically via a prefix of the
path name. This strategy is used in the HPRC. Including sample information
in the path name makes the graph and the FASTA that it is built from
contain identical sequence information. Other kinds of annotation break
this relationship and render any tool that works on FASTA incompatible with
the graph.

**Comment by yuxuanyuan** [comment]
In v1.0.1, we have added a function to support GFA1 from such as your vg.

**Comment by yuxuanyuan** [comment]
I'm closing this now and feel free to reopen

**Comment by mictadlo** [comment]
Hi @yuxuanyuan , 
I have a similar file as @ekg, but unfortunately, the conversion failed on the desktop and the app version of your tool

```
Last login: Thu Aug 22 11:56:24 on ttys002

 

The default interactive shell is now zsh.

To update your account to use zsh, please run `chsh -s /bin/zsh`.

For more details, please visit https://support.apple.com/kb/HT208050.

(base) C02W40N4J1GQ:~ waterhop$ cd Downloads/panGraphViewer/panGraphViewerApp

(base) C02W40N4J1GQ:panGraphViewerApp waterhop$ ls

README.md                   panGraphViewerApp.py        scripts

config.ini                  requirements.txt

config_default.ini          requirements_windows.txt

(base) C02W40N4J1GQ:panGraphViewerApp waterhop$ conda create -n pangraphviewerapp python=3.10

Channels:

 - conda-forge

 - bioconda

 - defaults

Platform: osx-64

Collecting package metadata (repodata.json): done

Solving environment: done

 

## Package Plan ##

 

  environment location: /Users/waterhop/miniconda3/envs/pangraphviewerapp

 

  added / updated specs:

    - python=3.10

 

 

The following NEW packages will be INSTALLED:

 

  bzip2              conda-forge/osx-64::bzip2-1.0.8-hfdf4475_7 

  ca-certificates    conda-forge/osx-64::ca-certificates-2024.7.4-h8857fd0_0 

  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5 

  libsqlite          conda-forge/osx-64::libsqlite-3.46.0-h1b8f9f3_0 

  libzlib            conda-forge/osx-64::libzlib-1.3.1-h87427d6_1 

  ncurses            conda-forge/osx-64::ncurses-6.5-h5846eda_0 

  openssl            conda-forge/osx-64::openssl-3.3.1-h87427d6_2 

  pip                conda-forge/noarch::pip-24.2-pyhd8ed1ab_0 

  python             conda-forge/osx-64::python-3.10.14-h00d2728_0_cpython 

  readline           conda-forge/osx-64::readline-8.2-h9e318b2_1 

  setuptools         conda-forge/noarch::setuptools-72.2.0-pyhd8ed1ab_0 

  tk                 conda-forge/osx-64::tk-8.6.13-h1abcd95_1 

  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0 

  wheel              conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0 

  xz                 conda-forge/osx-64::xz-5.2.6-h775f41a_0 

 

 

Proceed ([y]/n)? y

 

 

Downloading and Extracting Packages:

 

Preparing transaction: done

Verifying transaction: done

Executing transaction: done

#

# To activate this environment, use

#

#     $ conda activate pangraphviewerapp

#

# To deactivate an active environment, use

#

#     $ conda deactivate

 

(base) C02W40N4J1GQ:panGraphViewerApp waterhop$ conda activate pangraphviewerapp

(pangraphviewerapp) C02W40N4J1GQ:panGraphViewerApp waterhop$ pip install -r requirements.txt

Collecting PyQt5==5.12.3 (from -r requirements.txt (line 1))

  Downloading PyQt5-5.12.3-5.12.10-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_6_intel.whl.metadata (2.2 kB)

Collecting PyQtWebEngine==5.12.1 (from -r requirements.txt (line 2))

  Downloading PyQtWebEngine-5.12.1-5.12.10-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_6_intel.whl.metadata (1.7 kB)

Collecting Django==3.1.3 (from -r requirements.txt (line 3))

  Using cached Django-3.1.3-py3-none-any.whl.metadata (3.7 kB)

Collecting django-bootstrap4==22.1 (from -r requirements.txt (line 4))

  Using cached django_bootstrap4-22.1-py3-none-any.whl.metadata (3.5 kB)

Collecting requests==2.28.1 (from -r requirements.txt (line 5))

  Using cached requests-2.28.1-py3-none-any.whl.metadata (4.6 kB)

Collecting django-environ==0.9.0 (from -r requirements.txt (line 6))

  Using cached django_environ-0.9.0-py2.py3-none-any.whl.metadata (10 kB)

Collecting djangorestframework==3.13.1 (from -r requirements.txt (line 7))

  Using cached djangorestframework-3.13.1-py3-none-any.whl.metadata (10 kB)

Collecting configparser==5.2.0 (from -r requirements.txt (line 8))

  Using cached configparser-5.2.0-py3-none-any.whl.metadata (11 kB)

Collecting natsort==8.1.0 (from -r requirements.txt (line 9))

  Using cached natsort-8.1.0-py3-none-any.whl.metadata (20 kB)

Collecting networkx==2.6.3 (from -r requirements.txt (line 10))

  Using cached networkx-2.6.3-py3-none-any.whl.metadata (5.0 kB)

Collecting fontawesome-free==5.15.0 (from -r requirements.txt (line 11))

  Using cached fontawesome_free-5.15.0-py3-none-any.whl.metadata (1.6 kB)

Collecting bokeh==2.2.3 (from -r requirements.txt (line 12))

  Using cached bokeh-2.2.3-py3-none-any.whl

Collecting dna_features_viewer==3.1.1 (from -r requirements.txt (line 13))

  Using cached dna_features_viewer-3.1.1-py3-none-any.whl.metadata (2.0 kB)

Collecting pysam==0.19.1 (from -r requirements.txt (line 14))

  Using cached pysam-0.19.1-cp310-cp310-macosx_10_9_x86_64.whl.metadata (1.4 kB)

Collecting pandas==1.3.5 (from -r requirements.txt (line 15))

  Using cached pandas-1.3.5-cp310-cp310-macosx_10_9_x86_64.whl.metadata (12 kB)

Collecting whitenoise==6.2.0 (from -r requirements.txt (line 16))

  Using cached whitenoise-6.2.0-py3-none-any.whl.metadata (3.3 kB)

Collecting jinja2==3.0.0 (from -r requirements.txt (line 17))

  Using cached Jinja2-3.0.0-py3-none-any.whl.metadata (3.5 kB)

Collecting numpy==1.21.6 (from -r requirements.txt (line 18))

  Using cached numpy-1.21.6-cp310-cp310-macosx_10_9_x86_64.whl.metadata (2.1 kB)

Collecting biopython==1.79 (from -r requirements.txt (line 19))

  Using cached biopython-1.79-cp310-cp310-macosx_10_9_x86_64.whl.metadata (12 kB)

Collecting matplotlib==3.5.2 (from -r requirements.txt (line 20))

  Using cached matplotlib-3.5.2-cp310-cp310-macosx_10_9_x86_64.whl.metadata (6.7 kB)

Collecting sqlparse==0.4.2 (from -r requirements.txt (line 21))

  Using cached sqlparse-0.4.2-py3-none-any.whl.metadata (3.4 kB)

Collecting tornado==6.2 (from -r requirements.txt (line 22))

  Using cached tornado-6.2-cp37-abi3-macosx_10_9_x86_64.whl.metadata (2.5 kB)

Collecting PyQt5_sip<13,>=4.19.14 (from PyQt5==5.12.3->-r requirements.txt (line 1))

  Downloading PyQt5_sip-12.15.0-cp310-cp310-macosx_10_9_universal2.whl.metadata (421 bytes)

Collecting asgiref<4,>=3.2.10 (from Django==3.1.3->-r requirements.txt (line 3))

  Using cached asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)

Collecting pytz (from Django==3.1.3->-r requirements.txt (line 3))

  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)

Collecting beautifulsoup4>=4.8.0 (from django-bootstrap4==22.1->-r requirements.txt (line 4))

  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)

Collecting charset-normalizer<3,>=2 (from requests==2.28.1->-r requirements.txt (line 5))

  Using cached charset_normalizer-2.1.1-py3-none-any.whl.metadata (11 kB)

Collecting idna<4,>=2.5 (from requests==2.28.1->-r requirements.txt (line 5))

  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)

Collecting urllib3<1.27,>=1.21.1 (from requests==2.28.1->-r requirements.txt (line 5))

  Using cached urllib3-1.26.19-py2.py3-none-any.whl.metadata (49 kB)

Collecting certifi>=2017.4.17 (from requests==2.28.1->-r requirements.txt (line 5))

  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)

Collecting PyYAML>=3.10 (from bokeh==2.2.3->-r requirements.txt (line 12))

  Using cached PyYAML-6.0.2-cp310-cp310-macosx_10_9_x86_64.whl.metadata (2.1 kB)

Collecting python-dateutil>=2.1 (from bokeh==2.2.3->-r requirements.txt (line 12))

  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)

Collecting pillow>=7.1.0 (from bokeh==2.2.3->-r requirements.txt (line 12))

  Using cached pillow-10.4.0-cp310-cp310-macosx_10_10_x86_64.whl.metadata (9.2 kB)

Collecting packaging>=16.8 (from bokeh==2.2.3->-r requirements.txt (line 12))

  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)

Collecting typing-extensions>=3.7.4 (from bokeh==2.2.3->-r requirements.txt (line 12))

  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)

Collecting MarkupSafe>=2.0.0rc2 (from jinja2==3.0.0->-r requirements.txt (line 17))

  Using cached MarkupSafe-2.1.5-cp310-cp310-macosx_10_9_x86_64.whl.metadata (3.0 kB)

Collecting cycler>=0.10 (from matplotlib==3.5.2->-r requirements.txt (line 20))

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)

Collecting fonttools>=4.22.0 (from matplotlib==3.5.2->-r requirements.txt (line 20))

  Using cached fonttools-4.53.1-cp310-cp310-macosx_10_9_universal2.whl.metadata (162 kB)

Collecting kiwisolver>=1.0.1 (from matplotlib==3.5.2->-r requirements.txt (line 20))

  Using cached kiwisolver-1.4.5-cp310-cp310-macosx_10_9_x86_64.whl.metadata (6.4 kB)

Collecting pyparsing>=2.2.1 (from matplotlib==3.5.2->-r requirements.txt (line 20))

  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)

Collecting soupsieve>1.2 (from beautifulsoup4>=4.8.0->django-bootstrap4==22.1->-r requirements.txt (line 4))

  Using cached soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)

Collecting six>=1.5 (from python-dateutil>=2.1->bokeh==2.2.3->-r requirements.txt (line 12))

  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)

WARNING: The candidate selected for download or install is a yanked version: 'fontawesome-free' candidate (version 5.15.0 at https://files.pythonhosted.org/packages/6f/3a/98383624239a75c57f37c8846e627e32848b67c50da18b5b6c5a3c02131b/fontawesome_free-5.15.0-py3-none-any.whl (from https://pypi.org/simple/fontawesome-free/))

Reason for being yanked: <none given>

Downloading PyQt5-5.12.3-5.12.10-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_6_intel.whl (39.8 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.8/39.8 MB 3.3 MB/s eta 0:00:00

Downloading PyQtWebEngine-5.12.1-5.12.10-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_6_intel.whl (56.8 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 MB 3.4 MB/s eta 0:00:00

Using cached Django-3.1.3-py3-none-any.whl (7.8 MB)

Using cached django_bootstrap4-22.1-py3-none-any.whl (24 kB)

Using cached requests-2.28.1-py3-none-any.whl (62 kB)

Using cached django_environ-0.9.0-py2.py3-none-any.whl (17 kB)

Using cached djangorestframework-3.13.1-py3-none-any.whl (958 kB)

Using cached configparser-5.2.0-py3-none-any.whl (19 kB)

Using cached natsort-8.1.0-py3-none-any.whl (37 kB)

Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)

Using cached fontawesome_free-5.15.0-py3-none-any.whl (21.0 MB)

Using cached dna_features_viewer-3.1.1-py3-none-any.whl (30 kB)

Using cached pysam-0.19.1-cp310-cp310-macosx_10_9_x86_64.whl (3.2 MB)

Using cached pandas-1.3.5-cp310-cp310-macosx_10_9_x86_64.whl (11.3 MB)

Using cached whitenoise-6.2.0-py3-none-any.whl (19 kB)

Using cached Jinja2-3.0.0-py3-none-any.whl (133 kB)

Using cached numpy-1.21.6-cp310-cp310-macosx_10_9_x86_64.whl (17.0 MB)

Using cached biopython-1.79-cp310-cp310-macosx_10_9_x86_64.whl (2.3 MB)

Using cached matplotlib-3.5.2-cp310-cp310-macosx_10_9_x86_64.whl (7.3 MB)

Using cached sqlparse-0.4.2-py3-none-any.whl (42 kB)

Using cached tornado-6.2-cp37-abi3-macosx_10_9_x86_64.whl (419 kB)

Using cached asgiref-3.8.1-py3-none-any.whl (23 kB)

Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)

Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)

Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)

Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)

Using cached fonttools-4.53.1-cp310-cp310-macosx_10_9_universal2.whl (2.8 MB)

Using cached idna-3.7-py3-none-any.whl (66 kB)

Using cached kiwisolver-1.4.5-cp310-cp310-macosx_10_9_x86_64.whl (68 kB)

Using cached MarkupSafe-2.1.5-cp310-cp310-macosx_10_9_x86_64.whl (14 kB)

Using cached packaging-24.1-py3-none-any.whl (53 kB)

Using cached pillow-10.4.0-cp310-cp310-macosx_10_10_x86_64.whl (3.5 MB)

Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)

Downloading PyQt5_sip-12.15.0-cp310-cp310-macosx_10_9_universal2.whl (122 kB)

Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)

Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)

Using cached PyYAML-6.0.2-cp310-cp310-macosx_10_9_x86_64.whl (184 kB)

Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)

Using cached urllib3-1.26.19-py2.py3-none-any.whl (143 kB)

Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)

Using cached soupsieve-2.6-py3-none-any.whl (36 kB)

Installing collected packages: pytz, pysam, fontawesome-free, whitenoise, urllib3, typing-extensions, tornado, sqlparse, soupsieve, six, PyYAML, PyQt5_sip, pyparsing, pillow, packaging, numpy, networkx, natsort, MarkupSafe, kiwisolver, idna, fonttools, django-environ, cycler, configparser, charset-normalizer, certifi, requests, python-dateutil, PyQt5, jinja2, biopython, beautifulsoup4, asgiref, PyQtWebEngine, pandas, matplotlib, Django, bokeh, dna_features_viewer, djangorestframework, django-bootstrap4

Successfully installed Django-3.1.3 MarkupSafe-2.1.5 PyQt5-5.12.3 PyQt5_sip-12.15.0 PyQtWebEngine-5.12.1 PyYAML-6.0.2 asgiref-3.8.1 beautifulsoup4-4.12.3 biopython-1.79 bokeh-2.2.3 certifi-2024.7.4 charset-normalizer-2.1.1 configparser-5.2.0 cycler-0.12.1 django-bootstrap4-22.1 django-environ-0.9.0 djangorestframework-3.13.1 dna_features_viewer-3.1.1 fontawesome-free-5.15.0 fonttools-4.53.1 idna-3.7 jinja2-3.0.0 kiwisolver-1.4.5 matplotlib-3.5.2 natsort-8.1.0 networkx-2.6.3 numpy-1.21.6 packaging-24.1 pandas-1.3.5 pillow-10.4.0 pyparsing-3.1.2 pysam-0.19.1 python-dateutil-2.9.0.post0 pytz-2024.1 requests-2.28.1 six-1.16.0 soupsieve-2.6 sqlparse-0.4.2 tornado-6.2 typing-extensions-4.12.2 urllib3-1.26.19 whitenoise-6.2.0

(pangraphviewerapp) C02W40N4J1GQ:panGraphViewerApp waterhop$ ls

README.md                   panGraphViewerApp.py        scripts

config.ini                  requirements.txt

config_default.ini          requirements_windows.txt

(pangraphviewerapp) C02W40N4J1GQ:panGraphViewerApp waterhop$ python panGraphViewerApp.py 

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:99: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class WorkerSignals(QObject):

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:142: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class NodesInfoBrowser(QWidget):

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:148: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class about(QWidget):

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:155: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class vcf_2_rGFA(QWidget):

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:342: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class renameFaHeader(QWidget):

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:455: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class NodeShapes(QWidget):

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:659: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class GraphModify(QWidget):

/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py:803: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead

  class Main(QMainWindow):

2024-08-22 12:53:01.695 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.650 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.654 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.666 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.682 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.692 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.704 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.723 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.738 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.744 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.775 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.807 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.826 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.829 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.866 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.974 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:07.981 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:08.009 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:08.022 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:08.041 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:21,394 [INFO] Checking file: '/Users/waterhop/chnVSjapVSkorVSauVSusa.PanSN-1-19.fasta.gz.gfaffix.unchop.Ygs.view.gfa'

2024-08-22 12:53:27.579 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:53:37.276 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:54:03.735 python[58718:8999735] +[CATransaction synchronize] called within transaction

2024-08-22 12:54:08,246 [INFO] Checking folder: '/Users/waterhop/Documents/panGraph_outputxxx'

2024-08-22 12:54:21,712 [INFO] The input file is in GFA1 format and we are converting it to rGFA. Please wait!

Traceback (most recent call last):

  File "/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/scripts/gfa2rGFA.py", line 241, in <module>

    run.convert()

  File "/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/scripts/gfa2rGFA.py", line 139, in convert

    S[newId] = {'seq':rev_comp(S[nodeId]['seq']),'len':S[nodeId]['len']}

KeyError: '1779060'

2024-08-22 12:57:21,487 [INFO] Parsing rGFA

2024-08-22 12:58:24,436 [WARNING] !!!!! Not the wanted rGFA format. Please refer to 'Manual' to generate a proper one

2024-08-22 12:58:25,097 [INFO] Parsing rGFA

Traceback (most recent call last):

  File "/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/panGraphViewerApp.py", line 1405, in fmtcvtDone

    self.run = PanGraph(f"{self.gfa}", f"{self.outDir}")

  File "/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/scripts/panGraph.py", line 134, in __init__

    self.inf = self.parseRGFA(nodeIdDict)

  File "/Users/waterhop/Downloads/panGraphViewer/panGraphViewerApp/scripts/panGraph.py", line 175, in parseRGFA

    with open(self.gfa) as f:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/waterhop/Documents/panGraph_outputxxx/chnVSjapVSkorVSauVSusa.PanSN-1-19.fasta.gz.gfaffix.unchop.Ygs.view_converted.gfa'

Abort trap: 6
```
What did I miss?
